### ISSUE TITLE
Having trouble getting this working

### ISSUE THREAD

**Issue by DropzoneNinja** [robcowart/synesis_lite_snort#12]
All,

I just need a bit of configuration help. I've followed the installation directions as thoroughly as possible, but I must be doing something wrong. In Kibana I can see the log entries in Discover-snort-*, but when I go to the dashboard, everything is zero (except for the total counts) and when I hover over filter fields it displays a pop-up that says "doesn't exist on any documents in the snort-* index pattern"

I know it must be something easy, something I've overlooked, so if I could be directed where to look, that would be awesome.

Thanks in advance for any help,
Cheers,
Mike

**Comment by robcowart** [comment]
Closing all issues as this project has been archived.
