### ISSUE TITLE
typo in 20_filter_snort.logstash.conf

### ISSUE THREAD

**Issue by m5050** [robcowart/synesis_lite_snort#13]
https://github.com/robcowart/synesis_lite_snort/blob/56fd0cadad093b1b65daa0fa3bdf80387ff09c88/logstash/synlite_snort/conf.d/20_filter_snort.logstash.conf#L764

This line have a typo which have double brackets after the field reference (server_city).

**Comment by robcowart** [comment]
Closing all issues as this project has been archived.
